// Read example {label["fr"]["title"]}

// Label by language
export let label = {
    en: {
        title: "title",
        languageSelector: "I speak english!",
        welcomeMessage: "Welcome, please visit PAGES -> Pokédex to start discovering Pokémons!",
        menu_pages: "Pages",
        menu_pokedex: "Pokédex",
        menu_getStarted: "Get Started",
        menu_documentation: "Documentation",
        menu_viewSource: "View Source",
        loading: "Loading..",
        selectPokemon: "Select your Pokémon",
        quickSeaarch: "Quick search",
        name: "Nombre",
        image: "Image",
        pokemon: "Pokémon",
        discover: "Discover",
        viewImages: "View images",
        stats: "Stats",
        abilities: "Abilities",
        moves: "Moves",
        evolution: "Evolution",
        successful: "Successful",
        maskedAsFavourirte: "Marked as your favourite!",
        favourirteAlready: "This is your favourite already :)",
    },
    fr: {
        title: "titre",
        languageSelector: "Je parle français!",
        welcomeMessage: "Bienvenue, veuillez visiter PAGES -> Pokédex pour commencer à découvrir des Pokémon !",
        menu_pages: "Pages",
        menu_pokedex: "Pokédex",
        menu_getStarted: "Commencer",
        menu_documentation: "Documentation",
        menu_viewSource: "Voir la source",
        loading: "Chargement..",
        selectPokemon: "Sélectionnez votre Pokémon",
        quickSeaarch: "Recherche rapide",
        name: "Nom",
        image: "Image",
        pokemon: "Pokémon",
        discover: "Découvrir",
        viewImages: "Voir les images",
        stats: "Statistiques",
        abilities: "Capacités",
        moves: "Mouvements",
        evolution: "Évolution",
        successful: "À succès",
        maskedAsFavourirte: "Marqué comme votre favori !",
        favourirteAlready: "C'est déjà votre préféré :)",
    },
    null: {},
};

export let labelByName = {
    title: { en: "title", fr: "titre" },
    languageSelector: { en: "I speak english!", fr: "Je parle français!" },
    welcomeMessage: { en: "Welcome, please visit PAGES -> Pokédex to start discovering Pokémons!", fr: "Bienvenue, veuillez visiter PAGES -> Pokédex pour commencer à découvrir des Pokémon !" },
    menu_pages: { en: "Pages", fr: "Pages" },
    menu_pokedex: { en: "Pokédex", fr: "Pokédex" },
    menu_getStarted: { en: "Get Started", fr: "Commencer" },
    menu_documentation: { en: "Documentation", fr: "Documentation" },
    menu_viewSource: { en: "View Source", fr: "Voir la source" },
    loading: { en: "Loading..", fr: "Chargement.." },
    selectPokemon: { en: "Select your Pokémon", fr: "Sélectionnez votre Pokémon" },
    quickSeaarch: { en: "Quick search", fr: "Recherche rapide" },
    name: { en: "Nombre", fr: "Nom" },
    image: { en: "Image", fr: "Image" },
    pokemon: { en: "Pokémon", fr: "Pokémon" },
    discover: { en: "Discover", fr: "Découvrir" },
    viewImages: { en: "View images", fr: "Voir les images" },
    stats: { en: "Stats", fr: "Statistiques" },
    abilities: { en: "Abilities", fr: "Capacités" },
    moves: { en: "Moves", fr: "Mouvements" },
    evolution: { en: "Evolution", fr: "Évolution" },
};
